id: P6CD3C484
initial_creation_type: input
source_metadata:
  Title: Antarvyāpti
  Editor: '-'
  Publisher: Indian Council of Philosophical Research
  Place of Publication: New Delhi
  Year: '2002'
  Antarvyāptisamarthanam:
    Text Version: Romanized
    Input Personnel: Rashmi Shakya
    Input Date: June, 2017
    Proof Reader: Rashmi Shakya
    Supplier: Nagarjuna Institute of Buddhist Studies
    Sponsor: University of the West
created_at: '2022-03-08T16:47:50.993169'
last_modified_at: '2022-03-08T16:47:50.993178'
